---
# tasks file for certbot-cloudflare

- name: Get software for apt repository management.
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - curl
    - libffi-dev
    - libssl-dev
    - python3-apt
    - python3-dev
    - python3-pycurl

- name: check if certbot-dns-cloudflare plugin is installed
  shell: certbot plugins | grep dns-cloudflare
  register: cf_check
  ignore_errors: true
  changed_when: "cf_check is failed"

- name: Install certbot-dns-cloudflare
  block:
    - name: Trust certbot with root
      community.general.snap:
        name: certbot
        options:
          -  "trust-plugin-with-root=ok"
    - name: Install plugin
      community.general.snap:
        name: certbot-dns-cloudflare
    - name: Set connecitons
      block:
        - shell: "snap connect certbot:plugin certbot-dns-cloudflare"
        - shell: "snap connect certbot-dns-cloudflare:certbot-metadata certbot:certbot-metadata"
  when: cf_check is failed

- name: Create certbot folder - sudouser
  file:
    path: /etc/letsencrypt
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Certbot Template
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - { src: 'templates/confcloudflare.ini.j2', dest: '/etc/letsencrypt/dnscloudflare.ini' }
    - { src: 'templates/letsencrypt_cli.ini.j2', dest: '/etc/letsencrypt/cli.ini' }

- name: Create Certs.
  vars:
    certbot_create_if_missing: true
  include_role:
    name: geerlingguy.certbot
